src/Entity/Gallery.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
// * @ORM\Entity(repositoryClass="App\Repository\GalleryRepository")
 * @ORM\Entity()
 * @ORM\Table(name="gallery")
 */
class Gallery
{
	use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

	/**
	 * @ORM\Column(type="string", length=255, nullable=false)
	 */
	private $name;

	/**
	 * @ORM\Column(type="boolean", length=255, nullable=false, options={"default" : 1})
	 */
	private $active = true;

	/**
	 * @Doctrine\ORM\Mapping\OneToMany(targetEntity="App\Entity\Image", mappedBy="gallery", cascade={"persist", "remove"})
	 */
	private $images;

	public function __construct()
	{
		$this->images = new ArrayCollection();
	}

	public function getId()
	{
		return $this->id;
	}

	public function getName()
	{
		return $this->name;
	}

	public function setName($name): self
	{
		$this->name = $name;

		return $this;
	}

	public function setActive($active) : self
	{
		$this->active = $active;

		return $this;
	}

	public function getActive() : bool
	{
		return $this->active;
	}

	public function getImages()
	{
		return $this->images;
	}

	public function addImage(Image $image)
	{
		$this->images->add($image);

		return $this;
	}

	public function removeImage(Image $image)
	{
		$this->images->removeElement($image);

		return $this;
	}

	public function getMainImage()
	{
		if (count($this->getImages()) > 0) {
			return $this->getImages()->current();
		}

		return null;
	}
}

src/Form/Type/GalleryType.php
<?php

namespace App\Form\Type;

use App\Entity\ContactMessage;
use App\Entity\Gallery;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class GalleryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
	            'label' => 'name',
                'attr' => [
                    'placeholder' => 'enter_name'
                ],
	            'constraints' => [
	            	new NotBlank(),
		            new Length(['max' => 255])
	            ]
            ])
	        ->add('active', CheckboxType::class, [
	        	'label' => 'active_label',
	        	'required' => false,
	        ])
            ->add('save', SubmitType::class, ['label' => 'save'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
        	'class' => Gallery::class
        ]);
    }


    public function getBlockPrefix()
    {
        return 'gallery_type';
    }


}

src/Controller/GalleryController.php
<?php

namespace App\Controller;

use App\Entity\Gallery;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class GalleryController extends AbstractController
{
    public function index(Request $request) : Response
    {
	    $galleries = $this->getDoctrine()->getManager()->getRepository(Gallery::class)->findBy(['active' => true], ['name' => 'DESC']);
		if (count($galleries) == 0) {
			return $this->redirectToRoute('index');
		}

	    if (count($galleries) == 1) {
		    return $this->redirectToRoute('gallery_single', ['id' => $galleries[0]->getId()]);
	    }

        return $this->render('ciamek/gallery/index.html.twig', [
        	'galleries' => $galleries,
        ]);
    }

	public function single($id) :Response
	{
		$em = $this->getDoctrine()->getManager();
		$gallery = $em->getRepository(Gallery::class)->findOneBy(['id' => (int)$id, 'active' => true]);
		if (!$gallery) {
			throw new NotFoundHttpException('gallery not found');
		}

		return $this->render('ciamek/gallery/single.html.twig', [
			'gallery' => $gallery,
		]);
	}
}

templates/ciamek/gallery/index.html.twig
{% extends '/ciamek/baseFront.html.twig' %}

{% block content %}
    <!-- Title Section Starts -->
    <div class="title-section module">
        <div class="row">
            <div class="small-12 columns">
                <h1>{{ 'galleries'|trans }}</h1>
            </div><!-- Top Row /-->

            <div class="small-12 columns">
                <ul class="breadcrumbs">
                    <li><a href="/">{{ 'home'|trans }}</a></li>
                    <li>{{ 'galleries'|trans }}</li>
                </ul><!-- Breadcrumbs /-->
            </div><!-- Bottom Row /-->

        </div><!-- Row /-->
    </div>
    <!-- Title Section /-->
    <div class="projects grey-bg">
        <div class="row">
            <div class="projects-wrap small-12 columns">

                {% for gallery in galleries %}
                    {% if gallery.mainImage %}
                        <a href="{{ path('gallery_single', {'id': gallery.id}) }}" data-title="{{ gallery.name }}">
                            <div class="project">
                                <img class="gallery-thumb" src="{{ asset('/images/' ~ gallery.mainImage.filename)|imagine_filter('gallery_thumb') }}" alt="{{ gallery.name }}"/>
                                <div class="project-detail">
                                    <p>{{ gallery.name }}</p>
                                </div><!-- Project Detail /-->
                            </div><!-- Project /-->
                        </a>
                    {% endif %}
                {% endfor %}

            </div><!-- Projects Wrap /-->
        </div><!-- Row /-->
    </div>
    <!-- Projects /-->

{% endblock %}

templates/ciamek/gallery/single.html.twig
{% extends '/ciamek/baseFront.html.twig' %}

{% block content %}
    <!-- Title Section Starts -->
    <div class="title-section module">
        <div class="row">
            <div class="small-12 columns">
                <h1>{{ 'gallery'|trans }}</h1>
            </div><!-- Top Row /-->

            <div class="small-12 columns">
                <ul class="breadcrumbs">
                    <li><a href="/">{{ 'home'|trans }}</a></li>
                    <li><a href="{{ path('gallery_index') }}">{{ 'galleries'|trans }}</a></li>
                    <li>{{ gallery.name }}</li>
                </ul><!-- Breadcrumbs /-->
            </div><!-- Bottom Row /-->

        </div><!-- Row /-->
    </div>
    <!-- Title Section /-->
    <div class="projects grey-bg">
        <div class="row">
            <div class="projects-wrap small-12 columns">
                {% for image in gallery.images %}
                    <a href="{{ asset('/images/' ~ image.filename)|imagine_filter('gallery_image') }}" data-lightbox="plumber-gallery" data-title="{{ image.description }}">
                        <div class="project">
                            <img class="gallery-thumb" src="{{ asset('/images/' ~ image.filename)|imagine_filter('gallery_thumb') }}" alt="{{ image.alt }}"/>
                            <div class="project-detail">
                                <p>{{ image.description }}</p>
                            </div><!-- Project Detail /-->
                        </div><!-- Project /-->
                    </a>
                {% endfor %}

            </div><!-- Projects Wrap /-->
        </div><!-- Row /-->
    </div>
    <!-- Projects /-->

{% endblock %}